# Generated by Django 5.1.2 on 2024-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
